env:
  - CI=true
sudo: required
services:
  - docker

before_install:
  - docker build -t p0m1d0rka/docker-react -f Dockerfile.dev .

script:
  - docker run p0m1d0rka/docker-react npm run test -- --coverage