sudo: required
services:
  - docker

before_install:
  - docker build -t p0m1d0rka/docker-react -f Dockerfile.dev .

script:
  - docker run -e 'CI=true' p0m1d0rka/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-625295982156"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"