version: "3"
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      # do not try to map this folder
      - /app/node_modules
      # map everything in context to container
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev    
    volumes:
      - /app/node_modules
      - .:/app    
    command: ["npm", "run", "test"]
